name: main

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Tag docker image
      run: |
        docker pull avpeery/tech-talk-tutorial
        docker tag avpeery/tech-talk-tutorial avpeery/tech-talk-tutorial:${{ env.DOCKER_TAG }}
        docker push avpeery/tech-talk-tutorial:${{ env.DOCKER_TAG }}
      