name: main

on: 
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Dockerhub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push docker image
      env:
        DOCKER_TAG: ${{ secrets.DOCKER_TAG }}
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: avpeery/tech-talk-tutorial:${{ env.DOCKER_TAG }}
      